#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "The title of the project. Max 41 characters." # Instructor fills out
description    : > # Instructor fills out
  A short description of the project, Max 100 characters. 
long_description: | # Instructor fills out
  A longer description of the project around 6 - 10 lines (where a line is 80 characters). Written in markdown.
  Should mention and link to prerequisite courses.
time_needed: "45 minutes" # "30/45/60 minutes". # DataCamp fills out


#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 2 # 1 == R, 2 == python, 3 == sql # Automatically set
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites: # DataCamp fills out
  - 799
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard # DataCamp fills outs
# IDs for the topics the project covers
# See here for topic codes: https://www.dropbox.com/s/743poqhcos6q2x6/Screenshot%202018-10-31%2010.17.19.png?dl=0
topics:
  - 12

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : python # One of r, python or sql
# The name of the docker image used to run the course
from           : 'python-notebooks-prod:v1.1.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
